alter table public.profiles
  add column if not exists is_synthetic boolean not null default false;

alter table public.reviews
  add column if not exists is_synthetic boolean not null default false;

create table if not exists public.scoring_settings (
  id boolean primary key default true check (id),
  include_synthetic_reviews boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.scoring_settings (id, include_synthetic_reviews)
values (true, false)
on conflict (id) do nothing;

create index if not exists profiles_synthetic_idx
  on public.profiles (is_synthetic)
  where is_synthetic = true;

create index if not exists reviews_synthetic_idx
  on public.reviews (store_id, is_synthetic)
  where is_synthetic = true;

comment on column public.profiles.is_synthetic is
  'Marks development/demo accounts generated by supabase/seed.synthetic.sql.';

comment on column public.reviews.is_synthetic is
  'Marks development/demo reviews generated by supabase/seed.synthetic.sql.';

alter table public.scoring_settings enable row level security;

drop policy if exists "scoring settings admin read" on public.scoring_settings;
create policy "scoring settings admin read"
on public.scoring_settings for select
to authenticated
using (public.current_user_is_admin());

drop policy if exists "scoring settings admin update" on public.scoring_settings;
create policy "scoring settings admin update"
on public.scoring_settings for update
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

create or replace function public.include_synthetic_reviews_in_scoring()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select include_synthetic_reviews from public.scoring_settings where id = true),
    false
  );
$$;

create or replace function public.prevent_profile_privilege_escalation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_setting('app.bypass_profile_protection', true) = 'on' then
    return new;
  end if;

  if public.current_user_is_admin() then
    return new;
  end if;

  if auth.uid() is null or auth.uid() <> old.id then
    raise exception 'Profile updates are limited to the profile owner.';
  end if;

  new.trust_score := old.trust_score;
  new.review_count := old.review_count;
  new.five_star_ratio := old.five_star_ratio;
  new.average_score_given := old.average_score_given;
  new.average_review_length := old.average_review_length;
  new.report_count := old.report_count;
  new.hidden_review_count := old.hidden_review_count;
  new.is_admin := old.is_admin;
  new.is_synthetic := old.is_synthetic;
  return new;
end;
$$;

create or replace function public.prevent_review_moderation_escalation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_setting('app.bypass_review_maintenance', true) = 'on' then
    return new;
  end if;

  if public.current_user_is_admin() then
    return new;
  end if;

  if auth.uid() is null or auth.uid() <> old.user_id then
    raise exception 'Review updates are limited to the review owner.';
  end if;

  new.user_id := old.user_id;
  new.store_id := old.store_id;
  new.is_hidden := old.is_hidden;
  new.excluded_from_score := old.excluded_from_score;
  new.is_synthetic := old.is_synthetic;
  return new;
end;
$$;

create or replace function public.get_peer_average(
  input_region text,
  input_category text
)
returns numeric
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  peer_average numeric;
  peer_review_count int;
begin
  select
    round(sum(store_raw_score * review_count) / nullif(sum(review_count), 0), 4),
    coalesce(sum(review_count), 0)::int
  into peer_average, peer_review_count
  from (
    select
      s.id,
      count(r.id)::int as review_count,
      sum(r.review_score * r.quality_weight * public.calculate_user_trust_weight(r.user_id))
        / nullif(sum(r.quality_weight * public.calculate_user_trust_weight(r.user_id)), 0)
        as store_raw_score
    from public.stores s
    join public.reviews r on r.store_id = s.id
    where s.region = input_region
      and s.category = input_category
      and r.is_hidden = false
      and r.excluded_from_score = false
      and (public.include_synthetic_reviews_in_scoring() or r.is_synthetic = false)
    group by s.id
  ) scoped;

  if peer_review_count >= 30 and peer_average is not null then
    return peer_average;
  end if;

  select
    round(sum(store_raw_score * review_count) / nullif(sum(review_count), 0), 4),
    coalesce(sum(review_count), 0)::int
  into peer_average, peer_review_count
  from (
    select
      s.id,
      count(r.id)::int as review_count,
      sum(r.review_score * r.quality_weight * public.calculate_user_trust_weight(r.user_id))
        / nullif(sum(r.quality_weight * public.calculate_user_trust_weight(r.user_id)), 0)
        as store_raw_score
    from public.stores s
    join public.reviews r on r.store_id = s.id
    where s.category = input_category
      and r.is_hidden = false
      and r.excluded_from_score = false
      and (public.include_synthetic_reviews_in_scoring() or r.is_synthetic = false)
    group by s.id
  ) scoped;

  if peer_review_count >= 30 and peer_average is not null then
    return peer_average;
  end if;

  select
    round(sum(store_raw_score * review_count) / nullif(sum(review_count), 0), 4),
    coalesce(sum(review_count), 0)::int
  into peer_average, peer_review_count
  from (
    select
      s.id,
      count(r.id)::int as review_count,
      sum(r.review_score * r.quality_weight * public.calculate_user_trust_weight(r.user_id))
        / nullif(sum(r.quality_weight * public.calculate_user_trust_weight(r.user_id)), 0)
        as store_raw_score
    from public.stores s
    join public.reviews r on r.store_id = s.id
    where r.is_hidden = false
      and r.excluded_from_score = false
      and (public.include_synthetic_reviews_in_scoring() or r.is_synthetic = false)
    group by s.id
  ) scoped;

  if peer_review_count >= 30 and peer_average is not null then
    return peer_average;
  end if;

  return coalesce(peer_average, 3.0);
end;
$$;

create or replace function public.refresh_store_score_cache(input_store_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_store public.stores%rowtype;
  visible_review_count int := 0;
  raw numeric := 0;
  bayesian_raw numeric := 3;
  adjusted numeric := 3;
  ranking numeric := 0;
  taste_avg numeric := 0;
  service_avg numeric := 0;
  environment_avg numeric := 0;
  revisit_rate numeric := null;
  unique_reviewer_count int := 0;
  returning_reviewer_count int := 0;
  peer_avg numeric := 3;
  avg_user_weight numeric := 1;
  revisit_score numeric := 0;
  trust_score numeric := 3;
  trust_label text := 'unknown';
begin
  select * into target_store from public.stores where id = input_store_id;

  if not found then
    return;
  end if;

  select
    count(*)::int,
    coalesce(sum(review_score * final_weight_calc) / nullif(sum(final_weight_calc), 0), 0),
    coalesce(sum(taste_score * final_weight_calc) / nullif(sum(final_weight_calc), 0), 0),
    coalesce(sum(service_score * final_weight_calc) / nullif(sum(final_weight_calc), 0), 0),
    coalesce(sum(environment_score * final_weight_calc) / nullif(sum(final_weight_calc), 0), 0),
    coalesce(avg(user_weight_calc), 1)
  into
    visible_review_count,
    raw,
    taste_avg,
    service_avg,
    environment_avg,
    avg_user_weight
  from (
    select
      r.*,
      public.calculate_user_trust_weight(r.user_id) as user_weight_calc,
      r.quality_weight * public.calculate_user_trust_weight(r.user_id) as final_weight_calc
    from public.reviews r
    where r.store_id = input_store_id
      and r.is_hidden = false
      and r.excluded_from_score = false
      and (public.include_synthetic_reviews_in_scoring() or r.is_synthetic = false)
      and r.review_score is not null
  ) weighted_reviews;

  select
    count(*)::int,
    coalesce(
      count(*) filter (
        where valid_review_count >= 2
          and last_review_at - first_review_at >= interval '24 hours'
      ),
      0
    )::int
  into unique_reviewer_count, returning_reviewer_count
  from (
    select
      r.user_id,
      count(*)::int as valid_review_count,
      min(r.created_at) as first_review_at,
      max(r.created_at) as last_review_at
    from public.reviews r
    where r.store_id = input_store_id
      and r.is_hidden = false
      and r.excluded_from_score = false
      and (public.include_synthetic_reviews_in_scoring() or r.is_synthetic = false)
    group by r.user_id
  ) reviewer_stats;

  if unique_reviewer_count >= 3 then
    revisit_rate := returning_reviewer_count::numeric / nullif(unique_reviewer_count, 0);
  else
    revisit_rate := null;
  end if;

  peer_avg := public.get_peer_average(target_store.region, target_store.category);
  bayesian_raw := ((visible_review_count * raw) + (20 * peer_avg)) / (visible_review_count + 20);
  adjusted := least(5.0, greatest(1.0, 3 + (0.8 * (bayesian_raw - peer_avg))));
  revisit_score := least(5.0, greatest(0.0, coalesce(revisit_rate, 0) * 5));
  trust_score := least(5.0, greatest(1.0, 1 + (4 * ((avg_user_weight - 0.7) / 0.6))));

  if visible_review_count = 0 then
    trust_label := 'unknown';
  elsif avg_user_weight >= 1.1 then
    trust_label := 'high';
  elsif avg_user_weight >= 0.95 then
    trust_label := 'medium';
  else
    trust_label := 'low';
  end if;

  ranking := (adjusted * 0.75) + (revisit_score * 0.10) + (trust_score * 0.15);

  if visible_review_count < 5 or target_store.ranking_limited then
    ranking := 0;
  end if;

  insert into public.store_score_cache (
    store_id,
    raw_score,
    bayesian_raw_score,
    adjusted_score,
    ranking_score,
    taste_score,
    service_score,
    environment_score,
    review_count,
    revisit_rate,
    unique_reviewer_count,
    returning_reviewer_count,
    trust_level,
    peer_average_raw_score,
    updated_at
  )
  values (
    input_store_id,
    round(raw, 4),
    round(bayesian_raw, 4),
    round(adjusted, 4),
    round(ranking, 4),
    round(taste_avg, 4),
    round(service_avg, 4),
    round(environment_avg, 4),
    visible_review_count,
    case when revisit_rate is null then null else round(revisit_rate, 4) end,
    unique_reviewer_count,
    returning_reviewer_count,
    trust_label,
    round(peer_avg, 4),
    now()
  )
  on conflict (store_id) do update
  set
    raw_score = excluded.raw_score,
    bayesian_raw_score = excluded.bayesian_raw_score,
    adjusted_score = excluded.adjusted_score,
    ranking_score = excluded.ranking_score,
    taste_score = excluded.taste_score,
    service_score = excluded.service_score,
    environment_score = excluded.environment_score,
    review_count = excluded.review_count,
    revisit_rate = excluded.revisit_rate,
    unique_reviewer_count = excluded.unique_reviewer_count,
    returning_reviewer_count = excluded.returning_reviewer_count,
    trust_level = excluded.trust_level,
    peer_average_raw_score = excluded.peer_average_raw_score,
    updated_at = now();
end;
$$;

create or replace function public.set_synthetic_reviews_included(include_reviews boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.scoring_settings (id, include_synthetic_reviews, updated_at)
  values (true, include_reviews, now())
  on conflict (id) do update
  set
    include_synthetic_reviews = excluded.include_synthetic_reviews,
    updated_at = now();

  perform public.refresh_all_store_scores();
end;
$$;

revoke all on function public.set_synthetic_reviews_included(boolean) from public, anon, authenticated;

create or replace function public.set_synthetic_reviews_excluded(exclude_reviews boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.set_synthetic_reviews_included(not exclude_reviews);
end;
$$;

revoke all on function public.set_synthetic_reviews_excluded(boolean) from public, anon, authenticated;
